# Generated by Django 6.0.3 on 2026-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquerito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('cargo_pastoral', models.CharField(max_length=100)),
                ('igreja_local', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('formacao_teologica', models.CharField(max_length=100)),
                ('formacao_academica', models.CharField(max_length=100)),
                ('cargo_igreja', models.CharField(max_length=10)),
                ('status_membro', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
